### ISSUE TITLE
FX Module To-Do List

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge-rack#437]
- [x] SampleRate Change - do we rebuild properly?
- [x] Check all the value displays and port labels for consistency, especially clocks and sidebands
- [x] Modulation Depth Display on ModRing parameters calculated via surge
